using System.Data;
using Dapper;

namespace NAxonFramework.EventHandling.Saga.Repository.Ado
{
    public class HsqlSagaSqlSchema : GenericSagaSqlSchema
    {
        public override void SqlCreateTableAssocValueEntry(IDbConnection connection)
        {
            connection.Execute($"create table {_sagaSchema.AssociationValueEntryTable} (\n" +
                               "        id int not null GENERATED BY DEFAULT AS IDENTITY(start with 1),\n" +
                               "        associationKey varchar(255),\n" +
                               "        associationValue varchar(255),\n" +
                               "        sagaId varchar(255),\n" +
                               "        sagaType varchar(255),\n" +
                               "        primary key (id)\n" +
                               "    );\n");
        }
    }
}